### ISSUE TITLE
Error: Unsupported platform on OSX High Sierra

### ISSUE THREAD

**Issue by ghost** [bencevans/lumenaire#12]
here's the err I get trying to run the app build w/ `npm run platform-osx` command:
<img width="532" alt="screen shot 2018-03-28 at 9 55 20 am" src="https://user-images.githubusercontent.com/3918844/38016137-6130454e-326e-11e8-85e5-82c1f84f1708.png">
and here's my system config:
<img width="698" alt="screen shot 2018-03-28 at 9 56 18 am" src="https://user-images.githubusercontent.com/3918844/38016145-693aeb18-326e-11e8-9ba9-4ef14d9cc77e.png">

**Comment by bencevans** [comment]
Fixed by #9
