### ISSUE TITLE
Can't run the packager on ubuntu 16

### ISSUE THREAD

**Issue by slifin** [bencevans/lumenaire#5]
I've included the error log below:
http://pastebin.com/3VAf4v0Q 

It seems the paths have gone a bit crazy

**Comment by bencevans** [comment]
Hmm I'm on Ubuntu 16.04 and can't seem to replicate. Are you using a file-system other than Ext4?

**Comment by slifin** [comment]
I'm on ext4

**Comment by slifin** [comment]
I'll try and reinstall tomorrow to see if I can still replicate

**Comment by bencevans** [comment]
Cheers, I'm just trying it from scratch cloning into /tmp like yours...

**Comment by bencevans** [comment]
Hmm seems to be working ... [demo](https://asciinema.org/a/6ngw2ag9r90orqzvk45fdrfq9?t=0) :\ If you could give it another shot that'd be grand :smile_cat:
